---
- name: Installation et configuration d'Apache2 sur Debian 12
  hosts: webservers
  become: yes
  vars:
    apache_port: 80
    document_root: /var/www/html

  tasks:
    - name: Mise à jour du cache des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installation d'Apache2
      apt:
        name: apache2
        state: present

    - name: Démarrage et activation d'Apache2
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Vérification du statut d'Apache2
      systemd:
        name: apache2
        state: started
      register: apache_status

    - name: Création d'une page d'accueil personnalisée
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="fr">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Serveur Web Apache - Debian 12</title>
              <script src="https://cdn.tailwindcss.com"></script>
          </head>
          <body class="bg-gradient-to-br from-blue-50 to-indigo-100 min-h-screen">
              <div class="container mx-auto px-4 py-8">
            <div class="max-w-4xl mx-auto">
                <div class="bg-white rounded-lg shadow-xl p-8 mb-8">
              <div class="text-center mb-8">
                  <h1 class="text-4xl font-bold text-gray-800 mb-4">
                🚀 Serveur Apache Déployé !
                  </h1>
                  <p class="text-xl text-gray-600">
                Installation réussie avec Ansible sur Debian 12
                  </p>
              </div>
              
              <div class="grid md:grid-cols-2 gap-6">
                  <div class="bg-blue-50 p-6 rounded-lg">
                <h2 class="text-2xl font-semibold text-blue-800 mb-4">
                    📊 Informations Serveur
                </h2>
                <div class="space-y-3">
                    <div class="flex justify-between">
                  <span class="font-medium text-gray-700">Serveur:</span>
                  <span class="text-blue-600 font-mono">{{ ansible_host }}</span>
                    </div>
                    <div class="flex justify-between">
                  <span class="font-medium text-gray-700">Adresse IP:</span>
                  <span class="text-blue-600 font-mono">{{ ansible_default_ipv4.address }}</span>
                    </div>
                    <div class="flex justify-between">
                  <span class="font-medium text-gray-700">OS:</span>
                  <span class="text-blue-600">Debian 12</span>
                    </div>
                </div>
                  </div>
                  
                  <div class="bg-green-50 p-6 rounded-lg">
                <h2 class="text-2xl font-semibold text-green-800 mb-4">
                    ⏰ Déploiement
                </h2>
                <div class="space-y-3">
                    <div class="flex justify-between">
                  <span class="font-medium text-gray-700">Date:</span>
                  <span class="text-green-600 font-mono">{{ ansible_date_time.iso8601 }}</span>
                    </div>
                    <div class="flex justify-between">
                  <span class="font-medium text-gray-700">Statut:</span>
                  <span class="bg-green-100 text-green-800 px-3 py-1 rounded-full text-sm font-medium">
                      ✅ Actif
                  </span>
                    </div>
                </div>
                  </div>
              </div>
              
              <div class="mt-8 text-center">
                  <div class="bg-gradient-to-r from-purple-500 to-pink-500 text-white p-6 rounded-lg">
                <h3 class="text-2xl font-bold mb-2">🎉 Félicitations !</h3>
                <p class="text-lg">
                    Votre serveur Apache2 est maintenant opérationnel et prêt à servir vos applications web.
                </p>
                  </div>
              </div>
                </div>
            </div>
              </div>
          </body>
          </html>
        dest: "{{ document_root }}/index.html"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Vérification que le port 80 est ouvert
      wait_for:
        port: "{{ apache_port }}"
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 30

    - name: Affichage des informations de connexion
      debug:
        msg: |
          Apache2 installé avec succès !
          URL d'accès : http://{{ ansible_default_ipv4.address }}
          Statut du service : {{ apache_status.status.ActiveState }}

    - name: Installation de htop pour monitoring
      apt:
        name: htop
        state: present

    - name: Configuration des logs Apache avec rotation
      copy:
        content: |
          /var/log/apache2/*.log {
              daily
              missingok
              rotate 7
              compress
              notifempty
              create 644 www-data adm
              postrotate
                  systemctl reload apache2
              endscript
          }
        dest: /etc/logrotate.d/apache2-custom

    - name: Test de santé du serveur web
      uri:
        url: "http://localhost"
        method: GET
        status_code: 200
      retries: 3
      delay: 10
